
export const GET_USERINFO='GET_USERINFO'
export const RECORD_USERINFO='RECORD_USERINFO'
export const RECORD_CODE='RECORD_CODE'
export const SAVE_COUPON='SAVE_COUPON'
export const REMOVE_COUPON='REMOVE_COUPON'
